apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cmpapi
  namespace: cmpapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cmpapi
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 75